In [1]:
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
for i in data:
    print(i)

data
target
frame
target_names
DESCR
feature_names
filename
data_module


In [4]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
print(len(data['data']),len(data['target']))

150 150


In [9]:
input = data['data']
labels = data['target']

In [10]:
print(type(input), type(labels))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [11]:
import torch

In [68]:
torch.cuda.is_available()

True

In [67]:
input = torch.FloatTensor(input)
labels = torch.LongTensor(labels)

input = input.cuda()
labels = labels.cuda()

In [13]:
print(type(input), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [21]:
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [24]:
class LeNet(nn.Module):
    
    def __init__(self):
        super(LeNet, self).__init__()
        
        self.fc1 = nn.Linear(4,9)
        self.fc2 = nn.Linear(9,5)
        self.fc3 = nn.Linear(5,10)
        self.fc4 = nn.Linear(10, 3)
           
    def forward(self, x):
        
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        
        return x

In [69]:
net = LeNet()
net = net.cuda()

In [26]:
res_test = net(input[0])
print(res_test)

tensor([-0.0405,  0.1438,  0.1334], grad_fn=<AddBackward0>)


In [29]:
print(input[:4,], labels[:4,])

tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000]]) tensor([0, 0, 0, 0])


In [48]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [58]:
from tqdm import tqdm

In [70]:
for epoch in range(50):
    
    running_loss = 0.0
    
    for count in tqdm(range(30)):
        
        optimizer.zero_grad()
        
        output = net(input[count*5 : (count+1)*5 ])
        loss = criterion(output, labels[count*5 : (count+1)*5])
        loss.backward()
        optimizer.step()
        
        running_loss+=loss.item()
        
        if count%29 == 0:
            print('[%d,%5d] loss: %.3f' %
                 (epoch + 1, count+1, running_loss/29))
            
            running_loss = 0.0
print("done training")

 37%|██████████████████████████████                                                    | 11/30 [00:14<00:17,  1.06it/s]

[1,    1] loss: 0.043


100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:14<00:00,  2.07it/s]


[1,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 333.33it/s]


[2,    1] loss: 0.043
[2,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[3,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 197.40it/s]


[3,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[4,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 362.37it/s]


[4,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 392.71it/s]


[5,    1] loss: 0.043
[5,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[6,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 461.36it/s]


[6,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[7,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 454.55it/s]


[7,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 461.55it/s]

[8,    1] loss: 0.043
[8,   30] loss: 1.069



  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[9,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 389.62it/s]


[9,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[10,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 315.80it/s]


[10,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[11,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 374.99it/s]

[11,   30] loss: 1.069



  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[12,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 370.38it/s]


[12,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[13,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 303.03it/s]

[13,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 416.67it/s]


[14,    1] loss: 0.043
[14,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[15,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 405.40it/s]


[15,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[16,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 441.20it/s]


[16,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[17,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 379.76it/s]


[17,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[18,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 384.62it/s]


[18,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[19,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 379.75it/s]


[19,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[20,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 405.42it/s]


[20,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[21,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 441.17it/s]


[21,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[22,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 447.76it/s]


[22,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[23,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 447.74it/s]


[23,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[24,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 312.50it/s]


[24,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[25,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 416.68it/s]


[25,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[26,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 410.97it/s]


[26,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[27,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 454.55it/s]


[27,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[28,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 476.20it/s]


[28,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 422.55it/s]

[29,    1] loss: 0.043
[29,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 461.54it/s]

[30,    1] loss: 0.043
[30,   30] loss: 1.069



  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[31,    1] loss: 0.043
[31,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 476.18it/s]

[32,    1] loss: 0.043
[32,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 483.87it/s]

[33,    1] loss: 0.043
[33,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 461.54it/s]

[34,    1] loss: 0.043
[34,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 476.20it/s]

[35,    1] loss: 0.043
[35,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 468.75it/s]

[36,    1] loss: 0.043
[36,   30] loss: 1.069



  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[37,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 428.58it/s]


[37,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 422.54it/s]

[38,    1] loss: 0.043
[38,   30] loss: 1.069



  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[39,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 441.16it/s]


[39,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[40,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 410.97it/s]


[40,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 441.17it/s]

[41,    1] loss: 0.043
[41,   30] loss: 1.069



  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[42,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 447.52it/s]


[42,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[43,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 294.77it/s]


[43,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[44,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 337.07it/s]

[44,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 461.30it/s]


[45,    1] loss: 0.043
[45,   30] loss: 1.069


  0%|                                                                                           | 0/30 [00:00<?, ?it/s]

[46,    1] loss: 0.043


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 441.18it/s]


[46,   30] loss: 1.069


100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 468.72it/s]

[47,    1] loss: 0.043
[47,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 491.80it/s]

[48,    1] loss: 0.043
[48,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 483.85it/s]

[49,    1] loss: 0.043
[49,   30] loss: 1.069



100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 454.54it/s]

[50,    1] loss: 0.043
[50,   30] loss: 1.069
done training


In [60]:
torch.save(net, 'course_0.pth')

In [65]:
res = net(input)
print(res)

tensor([[ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00

In [62]:
model = torch.load('course_0.pth')
model.eval()

LeNet(
  (fc1): Linear(in_features=4, out_features=9, bias=True)
  (fc2): Linear(in_features=9, out_features=5, bias=True)
  (fc3): Linear(in_features=5, out_features=10, bias=True)
  (fc4): Linear(in_features=10, out_features=3, bias=True)
)

In [66]:
res = model(input)
print(res)

tensor([[ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00, -3.9628e-01, -1.8264e+00],
        [ 2.4948e+00